=== kangasta/fdbk/fdbk/schemas/topic-in.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "units": {
      "type": "object",
      "properties": {
        "field": { "type": "string"},
        "unit": { "type": "string"}
      },
      "required": ["field", "unit"]
    },
    "data_tools": {
      "type": "object",
      "properties": {
        "field": { "type": "string"},
        "method": { "type": "string"}
      },
      "required": ["field", "method"]
    }
  },
  "type": "object",
  "properties": {
    "id": {"type": "string"},
    "name": {"type": "string"},
    "type": {"type": "string"},
    "description": {"type": "string"},
    "fields": {
      "type": "array",
      "items": {"type": "string"}
    },
    "units": {
      "type": "array",
      "items": {"$ref": "#/definitions/units"}
    },
    "summary": {
      "type": "array",
      "items": {"$ref": "#/definitions/data_tools"}
    },
    "visualization": {
      "type": "array",
      "items": {"$ref": "#/definitions/data_tools"}
    },
    "form_submissions": {"type": "boolean"}
  },
  "required": ["name", "fields"]
}

=== kangasta/fdbk/examples/post_data/notopic.json
{
  "name": "No topic",
  "fields": [
    "field"
  ],
  "units": [
    {
      "field": "field",
      "unit": "unit"
    }
  ],
  "summary": [
    {
      "field": "field",
      "method": "latest"
    },
    {
      "field": "field",
      "method": "average"
    }
  ],
  "visualization": [
    {
      "field": "field",
      "method": "horseshoe"
    },
    {
      "field": "field",
      "method": "line"
    }
  ],
  "form_submissions": true
}

=== kangasta/fdbk/examples/post_data/topic.json
{
  "name": "APA",
  "description": "Taste review for the APA served in todays tasting.",
  "fields": [
    "stars",
    "text"
  ],
  "units": [
    {
      "field": "text",
      "unit": "text"
    },
    {
      "field": "stars",
      "unit": "stars"
    }
  ],
  "summary": [
    {
      "field": "stars",
      "method": "average"
    },
    {
      "field": "stars",
      "method": "latest"
    },
    {
      "field": "stars",
      "method": "last_truthy"
    },
    {
      "field": "stars",
      "method": "last_falsy"
    },
    {
      "field": "stars",
      "method": "not_supported"
    }
  ],
  "visualization": [
    {
      "field": "stars",
      "method": "doughnut"
    },
    {
      "field": "stars",
      "method": "line"
    }
  ],
  "form_submissions": true
}
